// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"parse-cookie/useQueryJsonStr":{"path":"parse-cookie/useQueryJsonStr","id":"parse-cookie/useQueryJsonStr","parentId":"@@/global-layout"},"parse-cookie/index":{"path":"parse-cookie","id":"parse-cookie/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'parse-cookie/useQueryJsonStr': React.lazy(() => import(/* webpackChunkName: "src__pages__parse-cookie__useQueryJsonStr" */'../../../src/pages/parse-cookie/useQueryJsonStr.tsx')),
'parse-cookie/index': React.lazy(() => import(/* webpackChunkName: "src__pages__parse-cookie__index" */'../../../src/pages/parse-cookie/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/wilson/playgroud/my-tools/src/layouts/index.tsx')),
},
  };
}
